pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    Node_8:
      node_version: 8.x
    Node_10:
      node_version: 10.x

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: $(node_version)
  displayName: 'Install Node.js'

- script: |
    npm ci
    npm test
  displayName: 'Run tests'
